[project]
name = "accept-match-league-of-legend"
version = "1.0.0"
description = "Автоматическое принятие матча в League of Legends. Автоматический бан и пик чемпионов"
authors = [
    {name = "Евгений Лавров", email = "i@evgenylavrov.ru"}
]
requires-python = ">=3.11"
dependencies = [
    "eel>=0.18.2",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
    "rich>=14.2.0",
]

[tool.project-updater]
update_url = "https://api.github.com/repos/lavrocoder/accept_match_league_of_legend/releases/latest"
critical_files = [
    "config/pick_and_ban_for_roles.txt",
]
